var premadeWindowObjects = {
    FileAddWindow:{
        title:"Add menu",
        id:"add_menu",
        icon_dir:"images/icons/add_menu_icon.ico",
        width:400,
        height:400,
        center:true,
        center_elements:true,
        content:[
            {
                tag:"label",
                content:"New file/folder name:"
            },
            {
                tag:"br"  
            },
            {
                tag:"input",
                class:"add_menu_arg",
                type:"text",
                name:"name_in"
            },
            {
                tag:"label",
                content:"Directory(name of folder to):"
            },
            {
                tag:"br"  
            },
            {
                tag:"input",
                class:"add_menu_arg",
                type:"text",
                name:"dir"
            },
            {
                tag:"br"  
            },
            {
                tag:"select",
                class:"add_menu_arg",
                name:"type",
                options:[
                    {
                        content:"File",
                        value:"file"
                    },
                    {
                        content:"Folder",
                        value:"folder"
                    },
                    {
                        content:"Sprite",
                        value:"sprite"
                    }
                ]
            },
            {
                tag:"button",
                content:"Add",
                name:"add",
                onclick:"AddNewFileButton()",
            } 
        ]
    }
}